In [35]:
import geopandas as gpd
import pandas as pd
import os
from shapely.geometry import LineString

In [3]:
os.chdir('D:/bachelors/datasets/')

In [21]:
graphs = [
    gpd.read_file(
        'analysis/yearly_graphs_v4/total/' + i
    ) for i in os.listdir('analysis/yearly_graphs_v4/total/') if 'edges' in i and 'gpkg' in i
]

In [29]:
graphs[0]

,index,local_1,local_2,flow,lat_start,lon_start,lat_finish,lon_finish,distance,flow_weighted,geometry
0,0,'s-Hertogenbosch,Aalburg,0.012788,51.716578,5.354612,51.745721,5.068460,20.033939,0.004070,"LINESTRING (5.35461 51.71658, 5.06846 51.74572)"
1,1,'s-Hertogenbosch,Alkmaar,0.005115,51.716578,5.354612,52.600515,4.804279,105.319220,0.000310,"LINESTRING (5.35461 51.71658, 4.80428 52.60051)"
2,2,'s-Hertogenbosch,Almere,0.010230,51.716578,5.354612,52.366282,5.249946,72.647177,0.000898,"LINESTRING (5.35461 51.71658, 5.24995 52.36628)"
3,3,'s-Hertogenbosch,Amersfoort,0.002558,51.716578,5.354612,52.173152,5.388570,50.854848,0.000321,"LINESTRING (5.35461 51.71658, 5.38857 52.17315)"
4,4,'s-Hertogenbosch,Amsterdam,0.008951,51.716578,5.354612,52.371662,4.891125,79.524314,0.000718,"LINESTRING (5.35461 51.71658, 4.89113 52.37166)"
...,...,...,...,...,...,...,...,...,...,...,...
7129,7408,Zoetermeer,Zwijndrecht,0.002558,52.060067,4.490129,51.821506,4.606817,27.730122,0.000588,"LINESTRING (4.49013 52.06007, 4.60682 51.82151)"
7130,7409,Zuidplas,Zwijndrecht,0.007673,51.998539,4.609005,51.821506,4.606817,19.698251,0.002483,"LINESTRING (4.60900 51.99854, 4.60682 51.82151)"
7131,7410,Zutphen,Zwolle,0.002558,52.136103,6.241262,52.518026,6.124732,43.234181,0.000377,"LINESTRING (6.24126 52.13610, 6.12473 52.51803)"
7132,7411,Zwartewaterland,Zwolle,0.060102,52.601674,6.070748,52.518026,6.124732,10.002212,0.038310,"LINESTRING (6.07075 52.60167, 6.12473 52.51803)"
7133,7412,Zwijndrecht,Zwolle,0.002558,51.821506,4.606817,52.518026,6.124732,129.579163,0.000126,"LINESTRING (4.60682 51.82151, 6.12473 52.51803)"

In [33]:
import json
with open('Variables/mappers/coordinates_map_final.json') as infile:
    coordinates_map = json.load(infile)

In [40]:
def get_geoLines(edge_list):
    return gpd.GeoDataFrame(
        edge_list,
        geometry = [
            LineString([(lon_start, lat_start),
                       (lon_finish, lat_finish)]) for lat_start, lon_start, lat_finish, lon_finish in zip(edge_list.lat_start,
                                                                                       edge_list.lon_start,
                                                                                       edge_list.lat_finish,
                                                                                       edge_list.lon_finish)],
        crs = {'init' : 'epsg:4326'}
    )


def get_geoPoints(node_list):
    return gpd.GeoDataFrame(
        node_list,
        geometry = [Point(xy) for xy in zip(node_list.lon, node_list.lat)],
        crs = {'init' : 'epsg:4326'}
    )

In [37]:
graph_dev = get_geoLines(
    pd.concat(graphs).groupby(['local_1', 'local_2'])['flow'].std().reset_index().dropna().assign(
        lat_start = lambda frame: frame.local_1.map(coordinates_map).str['lat'],
        lon_start = lambda frame: frame.local_1.map(coordinates_map).str['lon'],
        lat_finish = lambda frame: frame.local_2.map(coordinates_map).str['lat'],
        lon_finish = lambda frame: frame.local_2.map(coordinates_map).str['lon']
    )
)

node_dev = get_geoPoints(
    pd.concat()
)

In [39]:
graph_dev.to_file('analysis/link_deviation.gpkg', driver = 'GPKG')

CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE "rtree_link_deviation_geom" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'

Exception ignored in: 'fiona._shim.gdal_flush_cache'
Traceback (most recent call last):
  File "fiona/_err.pyx", line 201, in fiona._err.GDALErrCtxManager.__exit__
fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE "rtree_link_deviation_geom" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'

In [34]:
pd.concat(graphs).groupby(['local_1', 'local_2'])['flow'].std().reset_index().dropna().assign(
    lat_start = lambda frame: frame.local_1.map(coordinates_map).str['lat'],
    lon_start = lambda frame: frame.local_1.map(coordinates_map).str['lon'],
    lat_finish = lambda frame: frame.local_2.map(coordinates_map).str['lat'],
    lon_finish = lambda frame: frame.local_2.map(coordinates_map).str['lon'],
).assign(
    geometry = lambdabda frame: frame.apply(lambda row: LineString(row['lon_start']))
)

,local_1,local_2,flow,lat_start,lon_start,lat_finish,lon_finish
1,'s-Hertogenbosch,Aalburg,0.006093,51.716578,5.354612,51.745721,5.068460
2,'s-Hertogenbosch,Aalsmeer,0.001142,51.716578,5.354612,52.256592,4.756445
4,'s-Hertogenbosch,Alkmaar,0.008004,51.716578,5.354612,52.600515,4.804279
5,'s-Hertogenbosch,Almelo,0.003058,51.716578,5.354612,52.347764,6.666955
6,'s-Hertogenbosch,Almere,0.005480,51.716578,5.354612,52.366282,5.249946
...,...,...,...,...,...,...,...
22731,Zoetermeer,Zwolle,0.001593,52.060067,4.490129,52.518026,6.124732
22732,Zuidhorn,Zwolle,0.001695,53.271983,6.380709,52.518026,6.124732
22733,Zuidplas,Zwijndrecht,0.002869,51.998539,4.609005,51.821506,4.606817
22734,Zutphen,Zwolle,0.005805,52.136103,6.241262,52.518026,6.124732
22735,Zwartewaterland,Zwolle,0.048077,52.601674,6.070748,52.518026,6.124732

In [22]:
from functools import reduce

In [23]:
reduce

In [25]:
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['local_1', 'local_2'],
                                            how='outer'), graphs)

In [26]:
df_merged

,index_x,local_1,local_2,flow_x,lat_start_x,lon_start_x,lat_finish_x,lon_finish_x,distance_x,flow_weighted_x,...,geometry_x,index_y,flow_y,lat_start_y,lon_start_y,lat_finish_y,lon_finish_y,distance_y,flow_weighted_y,geometry_y
0,0.0,'s-Hertogenbosch,Aalburg,0.012788,51.716578,5.354612,51.745721,5.068460,20.033939,0.004070,...,"LINESTRING (5.35461 51.71658, 5.06846 51.74572)",0.0,0.008475,51.716578,5.354612,51.745721,5.068460,20.033939,0.001611,"LINESTRING (5.35461 51.71658, 5.06846 51.74572)"
1,1.0,'s-Hertogenbosch,Alkmaar,0.005115,51.716578,5.354612,52.600515,4.804279,105.319220,0.000310,...,"LINESTRING (5.35461 51.71658, 4.80428 52.60051)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2,2.0,'s-Hertogenbosch,Almere,0.010230,51.716578,5.354612,52.366282,5.249946,72.647177,0.000898,...,"LINESTRING (5.35461 51.71658, 5.24995 52.36628)",2.0,0.008475,51.716578,5.354612,52.366282,5.249946,72.647177,0.000444,"LINESTRING (5.35461 51.71658, 5.24995 52.36628)"
3,3.0,'s-Hertogenbosch,Amersfoort,0.002558,51.716578,5.354612,52.173152,5.388570,50.854848,0.000321,...,"LINESTRING (5.35461 51.71658, 5.38857 52.17315)",4.0,0.008475,51.716578,5.354612,52.173152,5.388570,50.854848,0.000635,"LINESTRING (5.35461 51.71658, 5.38857 52.17315)"
4,4.0,'s-Hertogenbosch,Amsterdam,0.008951,51.716578,5.354612,52.371662,4.891125,79.524314,0.000718,...,"LINESTRING (5.35461 51.71658, 4.89113 52.37166)",5.0,0.033898,51.716578,5.354612,52.371662,4.891125,79.524314,0.001624,"LINESTRING (5.35461 51.71658, 4.89113 52.37166)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22732,NaN,Werkendam,Zevenaar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,5122.0,0.004237,51.767247,4.881854,51.925116,6.089204,85.035115,0.000190,"LINESTRING (4.88185 51.76725, 6.08920 51.92512)"
22733,NaN,Westervoort,Winterswijk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,5126.0,0.016949,51.957860,5.977853,51.968713,6.729774,51.696562,0.001249,"LINESTRING (5.97785 51.95786, 6.72977 51.96871)"
22734,NaN,Wijdemeren,Wijk bij Duurstede,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,5136.0,0.004237,52.225530,5.087596,51.989101,5.329061,31.076772,0.000519,"LINESTRING (5.08760 52.22553, 5.32906 51.98910)"
22735,NaN,Wijk bij Duurstede,Zederik,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,5137.0,0.008475,51.989101,5.329061,51.931954,5.016003,22.438905,0.001439,"LINESTRING (5.32906 51.98910, 5.01600 51.93195)"
22736,NaN,Zandvoort,Zoeterwoude,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,5149.0,0.008475,52.356823,4.543093,52.113818,4.514203,27.111509,0.001191,"LINESTRING (4.54309 52.35682, 4.51420 52.11382)"